name: Rancher Documentation
description: Documentation for Rancher

baseurl: ""

markdown: redcarpet

redcarpet:
  extensions: ["smart", "tables", "no_intra_emphasis", "autolink", "strikethrough", "superscript", "with_toc_data"]
  syntax_highlighter: rouge

kramdown: 
  syntax_highlighter: rouge
  input: GFM
permalink: pretty

gems:
  - jekyll-redirect-from